name: BuildAndRunTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - source/**
  pull_request:
    branches: [ "main" ]
    paths:
    - source/**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Lucene.Net.Linq.sln
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore Lucene.Net.Linq.sln

    - name: Build
      run: dotnet build --no-restore Lucene.Net.Linq.sln --property WarningLevel=0 

    - name: Test 8.0
      run: dotnet test --no-build --verbosity normal source/Lucene.Net.Linq.Tests/Lucene.Net.Linq.Tests.csproj --framework net8.0

    - name: Test 10.0
      run: dotnet test --no-build --verbosity normal source/Lucene.Net.Linq.Tests/Lucene.Net.Linq.Tests.csproj --framework net10.0
